# Site settings

# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: "MARIA MYSLIWIEC"
email: 'mdm153@pitt.edu'
description: "computer engineering student + aspiring software developer"
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://marmysl.github.io/" # the base hostname & protocol for your site

# Social Media
linkedin_username: 'mariamysl'
github_username: 'marmysl'
medium_username: 'mariamys'

#Sections
section_title: 'MY SPECS'
section_subtitle: 'some projects + other relevant things'

# Build settings
markdown: kramdown

#Pagination
plugins:
  - jekyll-paginate

paginate: 10

# Setup
footer_text: '© 2020 Maria Mysliwiec'
admin_name: 'Maria Mysliwiec'
google_analytics: "UA-176296435-1"
enable_contact: true

# Navigation menu
enable_nav: true
nav_item:
  - { url: '/', text: 'Home' }
  - { url: '/about', text: 'About' }

############################################################

### Contact Form
#Place the modal window template in any place you'd like the user to click for the contact form.
#The template will display a link to click for the contact form modal window:

#```liquid
#{% include contact.html %}
#{% include contact-modal.html %}
#```

### Animation Effects
#Animations with CSS classes are baked into the theme. To animate a section or element, simply add the animation classes:

#```html
#<div id="about-me" class="wow fadeIn">
#  I'm the coolest!
#</div>
#```

#For a complete list of animations, see http://daneden.github.io/animate.css/

### Pagination
#By default, pagination on the home page will activate after 10 posts. You can change this within `_config.yml`. You can add the pagination to other layouts with:

#```liquid
#  {% for post in paginator.posts %}
 #   {% include post-content.html %}
#  {% endfor %}

#  {% include pagination.html %}
#```
